### ISSUE TITLE
bio fetch with SRR accession shows HTTP error

### ISSUE THREAD

**Issue by akannan2987** [ialbert/bio#22]
Hello Albert,

Thanks for this bio package. I wanted to fetch the information for SRR10971381. However when run the command below, I get a HTTP bad reqest error. Would you know why. How should I resolve it?

**$ bio fetch SRR10971381**
_Output_
Error for SRR10971381, nuccore, gbwithparts, text: HTTP Error 400: Bad Request

On the other hand bio search SRR10971381 works fine....
akannan@nrnb226 ~/bioinformatics/work/biostar_handbook/covid_analysis
**$ bio search SRR10971381**
_output_
[
    {
        "run_accession": "SRR10971381",
        "sample_accession": "SAMN13922059",
        "first_public": "2020-02-05",
        "country": "China: Wuhan",
        "sample_alias": "Human-BALF",
        "fastq_bytes": "1160191847;1216048922",
        "read_count": "28282964",
        "library_name": "1",
        "library_strategy": "RNA-Seq",
        "library_source": "METATRANSCRIPTOMIC",
        "library_layout": "PAIRED",
        "instrument_platform": "ILLUMINA",
        "instrument_model": "Illumina MiniSeq",
        "study_title": "Complete genome of a novel coronavirus associated with severe human respiratory disease in Wuhan, China",
        "fastq_ftp": "ftp.sra.ebi.ac.uk/vol1/fastq/SRR109/081/SRR10971381/SRR10971381_1.fastq.gz;ftp.sra.ebi.ac.uk/vol1/fastq/SRR109/081/SRR10971381/SRR10971381_2.fastq.gz"
    }
]

Many thanks for your help.

Abhilash Kannan

**Comment by ialbert** [comment]
the fetch does not quite work yet for fetching SRR numbers (though it is planned to have it work), 

but I will put in a fix to notify you of this instead of attempting to access a different resource

to actually fetch you need either use the FTP links returned in the search or the sratools, I have recently written on short post on just how many confusing options are out there:

**Tutorial:How to get FASTQ reads from the Short Read Archive (SRA)**

* https://www.biostars.org/p/9493498/

**Comment by akannan2987** [comment]
Dear ialbert, thanks for your reply. Sure I will keep looking for your notification and see if it works at a later time point. 
Thanks for sharing this link. It is indeed helpful.
